<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ExportClientsSql extends Command
{
    protected $signature = 'clients:export-sql 
        {--output= : Full path output .sql file}
        {--chunk=500 : Row per INSERT batch}';

    protected $description = 'Export data klient (users.role=client) ke SQL dump untuk dipindah ke server lain.';

    public function handle(): int
    {
        if (! Schema::hasTable('users')) {
            $this->error('Tabel users tidak ditemukan.');
            return self::FAILURE;
        }

        $output = (string) ($this->option('output') ?: storage_path('app/exports/clients_only.sql'));
        $chunkSize = max(50, (int) $this->option('chunk'));
        $directory = dirname($output);
        if (! is_dir($directory)) {
            @mkdir($directory, 0777, true);
        }

        $columns = Schema::getColumnListing('users');
        if (empty($columns)) {
            $this->error('Kolom users tidak terbaca.');
            return self::FAILURE;
        }

        $count = User::query()->where('role', 'client')->count();
        if ($count <= 0) {
            $this->warn('Tidak ada data klient untuk diexport.');
            file_put_contents($output, "-- No client rows found\n");
            $this->line("File dibuat: {$output}");
            return self::SUCCESS;
        }

        $pdo = DB::getPdo();
        $quotedCols = implode(', ', array_map(fn (string $col) => "`{$col}`", $columns));

        $sql = [];
        $sql[] = '-- Auto-generated by clients:export-sql';
        $sql[] = '-- Generated at '.now()->format('Y-m-d H:i:s');
        $sql[] = 'SET FOREIGN_KEY_CHECKS=0;';
        $sql[] = "DELETE FROM `users` WHERE `role`='client';";

        $buffer = [];
        $processed = 0;

        User::query()
            ->where('role', 'client')
            ->orderBy('id')
            ->chunk($chunkSize, function ($rows) use (&$buffer, &$sql, &$processed, $columns, $quotedCols, $pdo): void {
                foreach ($rows as $row) {
                    $values = [];
                    foreach ($columns as $column) {
                        $value = $row->{$column};
                        if ($value === null) {
                            $values[] = 'NULL';
                        } elseif (is_bool($value)) {
                            $values[] = $value ? '1' : '0';
                        } elseif (is_int($value) || is_float($value)) {
                            $values[] = (string) $value;
                        } else {
                            $values[] = $pdo->quote((string) $value);
                        }
                    }

                    $buffer[] = '('.implode(', ', $values).')';
                    $processed++;
                }

                if (! empty($buffer)) {
                    $sql[] = "INSERT INTO `users` ({$quotedCols}) VALUES\n".implode(",\n", $buffer).';';
                    $buffer = [];
                }
            });

        $sql[] = 'SET FOREIGN_KEY_CHECKS=1;';
        $sql[] = '';
        file_put_contents($output, implode("\n", $sql));

        $this->info("Export selesai. Total klient: {$processed}");
        $this->line("Output: {$output}");

        return self::SUCCESS;
    }
}

